const ELECTRONICS = "Electronics";
const FISH = "Fish";
const FRUITS = "Fruits";
const VEGETABLES = "Vegetables";
const OTHER_FOOD = "Other Food";
const DRINKS = "Drinks";
const SWEETS = "Sweets & Desserts";
const KITCHEN = "Kitchen Appliances";

export interface Product {
  id: number;
  name: string;
  emoji: string;
  price: number;
  description: string;
  category:
    | typeof ELECTRONICS
    | typeof FISH
    | typeof FRUITS
    | typeof VEGETABLES
    | typeof OTHER_FOOD
    | typeof DRINKS
    | typeof SWEETS
    | typeof KITCHEN;
}

// next id: 67
export const products: Product[] = [
  // Electronics
  {
    id: 1,
    name: "Laptop",
    emoji: "💻",
    price: 999.99,
    description: "High-performance laptop",
    category: ELECTRONICS,
  },
  {
    id: 2,
    name: "Smartphone",
    emoji: "📱",
    price: 699.99,
    description: "Latest model smartphone",
    category: ELECTRONICS,
  },
  {
    id: 3,
    name: "Headphones",
    emoji: "🎧",
    price: 199.99,
    description: "Noise-canceling headphones",
    category: ELECTRONICS,
  },
  {
    id: 4,
    name: "Camera",
    emoji: "📸",
    price: 449.99,
    description: "Digital camera",
    category: ELECTRONICS,
  },

  // Fish
  {
    id: 5,
    name: "Blowfish",
    emoji: "🐡",
    price: 15.99,
    description: "Fresh blowfish",
    category: FISH,
  },
  {
    id: 6,
    name: "Tropical Fish",
    emoji: "🐠",
    price: 12.99,
    description: "Colorful tropical fish",
    category: FISH,
  },
  {
    id: 7,
    name: "Fish",
    emoji: "🐟",
    price: 9.99,
    description: "Fresh fish",
    category: FISH,
  },
  {
    id: 8,
    name: "Shrimp",
    emoji: "🦐",
    price: 18.99,
    description: "Fresh shrimp",
    category: FISH,
  },
  {
    id: 9,
    name: "Squid",
    emoji: "🦑",
    price: 16.99,
    description: "Fresh squid",
    category: FISH,
  },
  {
    id: 10,
    name: "Octopus",
    emoji: "🐙",
    price: 22.99,
    description: "Fresh octopus",
    category: FISH,
  },
  {
    id: 11,
    name: "Lobster",
    emoji: "🦞",
    price: 35.99,
    description: "Fresh lobster",
    category: FISH,
  },
  {
    id: 12,
    name: "Crab",
    emoji: "🦀",
    price: 28.99,
    description: "Fresh crab",
    category: FISH,
  },

  // Fruits
  {
    id: 13,
    name: "Apple",
    emoji: "🍎",
    price: 0.99,
    description: "Fresh red apple",
    category: FRUITS,
  },
  {
    id: 14,
    name: "Single banana",
    emoji: "🍌",
    price: 0.59,
    description: "Fresh banana",
    category: FRUITS,
  },
  {
    id: 66,
    name: "Bananas (bunch of six)",
    emoji: "🍌🍌",
    price: 2.89,
    description: "A bunch of six bananas",
    category: FRUITS,
  },
  {
    id: 15,
    name: "Orange",
    emoji: "🍊",
    price: 0.79,
    description: "Juicy orange",
    category: FRUITS,
  },
  {
    id: 16,
    name: "Lemon",
    emoji: "🍋",
    price: 0.69,
    description: "Fresh lemon",
    category: FRUITS,
  },
  {
    id: 17,
    name: "Pear",
    emoji: "🍐",
    price: 0.89,
    description: "Ripe pear",
    category: FRUITS,
  },
  {
    id: 18,
    name: "Peach",
    emoji: "🍑",
    price: 1.29,
    description: "Sweet peach",
    category: FRUITS,
  },
  {
    id: 19,
    name: "Grapes",
    emoji: "🍇",
    price: 3.99,
    description: "Fresh grapes",
    category: FRUITS,
  },
  {
    id: 20,
    name: "Strawberry",
    emoji: "🍓",
    price: 4.99,
    description: "Fresh strawberries",
    category: FRUITS,
  },
  {
    id: 21,
    name: "Blueberries",
    emoji: "🫐",
    price: 5.99,
    description: "Fresh blueberries",
    category: FRUITS,
  },
  {
    id: 22,
    name: "Watermelon",
    emoji: "🍉",
    price: 7.99,
    description: "Fresh watermelon",
    category: FRUITS,
  },
  {
    id: 23,
    name: "Coconut",
    emoji: "🥥",
    price: 3.99,
    description: "Fresh coconut",
    category: FRUITS,
  },

  // Vegetables
  {
    id: 24,
    name: "Carrot",
    emoji: "🥕",
    price: 0.99,
    description: "Fresh carrot",
    category: VEGETABLES,
  },
  {
    id: 25,
    name: "Broccoli",
    emoji: "🥦",
    price: 2.49,
    description: "Fresh broccoli",
    category: VEGETABLES,
  },
  {
    id: 26,
    name: "Cucumber",
    emoji: "🥒",
    price: 1.49,
    description: "Fresh cucumber",
    category: VEGETABLES,
  },
  {
    id: 27,
    name: "Lettuce",
    emoji: "🥬",
    price: 1.99,
    description: "Fresh lettuce",
    category: VEGETABLES,
  },
  {
    id: 28,
    name: "Potato",
    emoji: "🥔",
    price: 0.79,
    description: "Fresh potato",
    category: VEGETABLES,
  },
  {
    id: 29,
    name: "Tomato",
    emoji: "🍅",
    price: 0.99,
    description: "Fresh tomato",
    category: VEGETABLES,
  },
  {
    id: 30,
    name: "Corn",
    emoji: "🌽",
    price: 0.89,
    description: "Fresh corn",
    category: VEGETABLES,
  },
  {
    id: 31,
    name: "Garlic",
    emoji: "🧄",
    price: 0.99,
    description: "Fresh garlic",
    category: VEGETABLES,
  },
  {
    id: 32,
    name: "Onion",
    emoji: "🧅",
    price: 0.89,
    description: "Fresh onion",
    category: VEGETABLES,
  },
  {
    id: 33,
    name: "Bell Pepper",
    emoji: "🫑",
    price: 1.49,
    description: "Fresh bell pepper",
    category: VEGETABLES,
  },

  // Other Food
  {
    id: 34,
    name: "Bread",
    emoji: "🍞",
    price: 2.99,
    description: "Fresh bread",
    category: OTHER_FOOD,
  },
  {
    id: 35,
    name: "Cheese",
    emoji: "🧀",
    price: 4.99,
    description: "Premium cheese",
    category: OTHER_FOOD,
  },
  {
    id: 36,
    name: "Eggs (12x)",
    emoji: "🥚",
    price: 3.99,
    description: "Pack of a dozen eggs",
    category: OTHER_FOOD,
  },
  {
    id: 37,
    name: "Milk",
    emoji: "🥛",
    price: 2.99,
    description: "Fresh milk",
    category: DRINKS,
  },
  {
    id: 38,
    name: "Coffee",
    emoji: "☕",
    price: 4.99,
    description: "Premium coffee beans",
    category: DRINKS,
  },
  {
    id: 39,
    name: "Tea",
    emoji: "🫖",
    price: 3.99,
    description: "Assorted tea bags",
    category: DRINKS,
  },
  {
    id: 40,
    name: "Wine",
    emoji: "🍷",
    price: 15.99,
    description: "Red wine",
    category: DRINKS,
  },
  {
    id: 41,
    name: "Beer",
    emoji: "🍺",
    price: 8.99,
    description: "Craft beer 6-pack",
    category: DRINKS,
  },
  {
    id: 42,
    name: "Tropical Drink",
    emoji: "🍹",
    price: 6.99,
    description: "Mixed fruit cocktail",
    category: DRINKS,
  },
  {
    id: 43,
    name: "Ice Cream",
    emoji: "🍦",
    price: 3.99,
    description: "Vanilla ice cream",
    category: SWEETS,
  },
  {
    id: 44,
    name: "Cake",
    emoji: "🎂",
    price: 24.99,
    description: "Birthday cake",
    category: SWEETS,
  },
  {
    id: 45,
    name: "Chocolate Bar",
    emoji: "🍫",
    price: 2.99,
    description: "Dark chocolate",
    category: SWEETS,
  },
  {
    id: 46,
    name: "Cookie",
    emoji: "🍪",
    price: 1.99,
    description: "Chocolate chip cookies",
    category: SWEETS,
  },
  {
    id: 47,
    name: "Candy",
    emoji: "🍬",
    price: 0.99,
    description: "Assorted candies",
    category: SWEETS,
  },
  {
    id: 48,
    name: "Doughnut",
    emoji: "🍩",
    price: 1.49,
    description: "Glazed doughnut",
    category: SWEETS,
  },
  {
    id: 49,
    name: "Cupcake",
    emoji: "🧁",
    price: 2.99,
    description: "Frosted cupcake",
    category: SWEETS,
  },
  {
    id: 50,
    name: "Microwave",
    emoji: "🔥",
    price: 89.99,
    description: "Countertop microwave",
    category: KITCHEN,
  },
  {
    id: 51,
    name: "Toaster",
    emoji: "🍞",
    price: 29.99,
    description: "2-slice toaster",
    category: KITCHEN,
  },
  {
    id: 52,
    name: "Blender",
    emoji: "🥤",
    price: 49.99,
    description: "High-speed blender",
    category: KITCHEN,
  },
  {
    id: 53,
    name: "Rice Cooker",
    emoji: "🍚",
    price: 39.99,
    description: "Automatic rice cooker",
    category: KITCHEN,
  },
  {
    id: 54,
    name: "Coffee Maker",
    emoji: "☕",
    price: 59.99,
    description: "Programmable coffee maker",
    category: KITCHEN,
  },
  {
    id: 55,
    name: "Air Fryer",
    emoji: "🍗",
    price: 79.99,
    description: "Digital air fryer",
    category: KITCHEN,
  },
  {
    id: 56,
    name: "Smart Watch",
    emoji: "⌚",
    price: 299.99,
    description: "Fitness tracking smartwatch",
    category: ELECTRONICS,
  },
  {
    id: 57,
    name: "Tablet",
    emoji: "📱",
    price: 499.99,
    description: "10-inch tablet",
    category: ELECTRONICS,
  },
  {
    id: 58,
    name: "Gaming Console",
    emoji: "🎮",
    price: 399.99,
    description: "Latest gaming system",
    category: ELECTRONICS,
  },
  {
    id: 59,
    name: "Wireless Speaker",
    emoji: "🔊",
    price: 129.99,
    description: "Bluetooth speaker",
    category: ELECTRONICS,
  },
  {
    id: 60,
    name: "Sushi Roll",
    emoji: "🍱",
    price: 12.99,
    description: "Fresh sushi assortment",
    category: OTHER_FOOD,
  },
  {
    id: 61,
    name: "Pizza",
    emoji: "🍕",
    price: 14.99,
    description: "Large pepperoni pizza",
    category: OTHER_FOOD,
  },
  {
    id: 62,
    name: "Hamburger",
    emoji: "🍔",
    price: 8.99,
    description: "Classic cheeseburger",
    category: OTHER_FOOD,
  },
  {
    id: 63,
    name: "Hot Dog",
    emoji: "🌭",
    price: 4.99,
    description: "All-beef hot dog",
    category: OTHER_FOOD,
  },
  {
    id: 64,
    name: "Popcorn",
    emoji: "🍿",
    price: 3.99,
    description: "Movie theater popcorn",
    category: OTHER_FOOD,
  },
  {
    id: 65,
    name: "Pretzel",
    emoji: "🥨",
    price: 2.99,
    description: "Soft pretzel",
    category: OTHER_FOOD,
  },
];
